import {get, post, deleteRequest, patch} from "./index";

export const postCluster = p => post("/apis/cluster", p)
export const getCluster = p => get("/apis/cluster",p)
export const exitCluster = p => get("/apis/exit", p)
export const createMaster = p => post("/apis/master", p)
export const createNode = p => post("/apis/node", p)
export const deleteNode = (nodeName, p) => deleteRequest("/apis/node/" + nodeName, p)

export const cluster = p => get("/apis/cluster", p)
export const resourcesNums = p => get("/common/resources/nums", p)
export const nodes = p => get("/apis/nodes", p)
export const node = (name, p) => get("/apis/node/" + name, p)
export const podsByNode = (hostname, p) => get("/apis/node/" + hostname + "/pods", p)
export const allPods = p => get("/apis/pods", p)
export const podByName = (namespace, name, p) => get("/apis/" + namespace + "/pod/" + name, p)
export const addPod = (namespace, p) => post("/apis/" + namespace + "/pod", p)
export const deletePod = (namespace, name, p) => deleteRequest("/apis/" + namespace + "/pod/" + name, p)
export const namespacedPods = (namespace, p) => get("/apis/" + namespace + "/pods", p)
export const namespaces = p => get("/apis/namespaces", p)
export const namespace = p => post("/apis/namespace", p)
export const deleteNamespace = (namespace, p) => deleteRequest("/apis/namespace/" + namespace, p)
export const deploymentsForAllNamespaces = p => get("/apis/deployments", p)
export const addDeployment = (namespace, p) => post("/apis/" + namespace + "/deployment", p)
export const deleteDeployment = (namespace, name, p) => deleteRequest("/apis/" + namespace + "/deployment/" + name, p)
export const patchReplica = (namespace, name, p) => patch("/apis/" + namespace + "/deployment/" + name, p)
export const namespacedDeployments = (namespace, p) => get("/apis/" + namespace + "/deployments", p)
export const services = p => get("/apis/services", p)
export const addService = (namespace, p) => post("/apis/" + namespace + "/service", p)
export const deleteService = (namespace, name, p) => deleteRequest("/apis/" + namespace + "/service/" + name, p)
export const namespacedServices = (namespace, p) => get("/apis/" + namespace + "/services", p)